<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazor.Heroicons" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.0" />
    <PackageReference Include="TailwindMerge.NET" Version="1.2.0"/>
  </ItemGroup>

  <ItemGroup>
      <TypeScriptCompile Include="wwwroot\libs\types\dotnet-object-type.ts" />
      <TypeScriptCompile Include="wwwroot\libs\utils\theme-utils.ts" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="tsconfig.json" />
    <None Include="tsconfig.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\fonts\font.css" />
    <_ContentIncludedByDefault Remove="wwwroot\fonts\Geist-Bold.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\fonts\Geist-ExtraLight.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\fonts\Geist-Light.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\fonts\Geist-Medium.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\fonts\Geist-Regular.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\fonts\Geist-SemiBold.woff2" />
  </ItemGroup>

  <Import Project="..\..\.targets\bun\Install.targets" />
  <Import Project="..\..\.targets\bun\Build.targets" />

</Project>
