<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
    
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.11"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.11" PrivateAssets="all"/>
        <PackageReference Include="PublishSPAforGitHubPages.Build" Version="3.0.3" />
        <PackageReference Include="WMBlazorOverlayScrollbars" Version="1.0.0" />
    </ItemGroup>

    <ItemGroup Label="Setup LMS.Components">
        <ProjectReference Include="..\LMS.Components\LMS.Components.csproj" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Source\Features\ThemeSwitcher\ThemeSwitcher.razor" />
      <AdditionalFiles Include="Source\Pages\Home.razor" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Source\Shared\Features\ThemeSwitcher\ThemeSwitcher.razor" />
    </ItemGroup>

    <Import Project="..\..\.targets\bun\Install.targets" />
    <Import Project="..\..\.targets\bun\Build.targets" />
</Project>
